#!/bin/sh

. /etc/rc.conf

if [ -z "${cbsd_workdir}" ]; then
	echo "No cbsd_workdir initialized"
	exit 1
fi

case "$*" in
	--template)
			cache_file="${cbsd_workdir}/tmp/bhyve-templates.json"
			;;
	--vm)
			cache_file="${cbsd_workdir}/tmp/bhyve-vm.json"
			;;
	*)
			echo "usage: --vm or --template"
			exit 1
			;;
esac

if [ -r ${cache_file} ]; then
	cache_file_size=$( /usr/bin/stat -f "%z" ${cache_file} 2>/dev/null )
else
	cache_file_size=0
fi

if [ -r ${cache_file} -a ${cache_file_size} -gt 0 ]; then
	cat ${cache_file}
else
	cbsd compile_bhyve_profiles $* > ${cache_file}
	cat ${cache_file}
fi
